config/routes.rb
Rails.application.routes.draw do

  get '/profile', to: 'sessions#show', as: 'show'
  delete '/signout', to: 'sessions#destroy', as: 'signout'
  resources :widgets
  
  get '/stocks', to: 'stock#stock_detail', as: 'stock_detail'
  post '/stocks', to: 'stock#stock_detail', as: 'ticker'
  get '/mystocks', to: 'stock#stocks', as: 'mystocks'
  
  get '/calendar', to: 'calendar#calendar', as: 'calendar'
  post '/new_event', to: 'calendar#new_event', as: 'new_event'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/twitter/callback', to: 'sessions#create', as: 'callback'
  get '/auth/failure', to: 'sessions#error', as: 'failure'
  post '/writetweet', to: 'sessions#writetweet', as: 'write_tweet'
  post '/update_settings', to: 'sessions#update_settings', as: 'update_settings'
  resources :widgets

  root 'welcome#index'

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%=link_to('Twitter Stocks', show_path, html_options={class: "navbar-brand"})%>
    </div>
    <ul class="nav navbar-nav">
      <li>
        <%=link_to calendar_path do%>
          <span class="glyphicon glyphicon-calendar"></span> Calendar
        <% end %>
      </li>
      <li>
        <a href="#"><span class="glyphicon glyphicon-stats"></span> Stocks</a>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <a href="#" data-toggle = "modal" data-target="#settingsModal">
          <span class="glyphicon glyphicon-cog"></span>
        </a>
      </li>
      <li class="navbar-right">
        <%= link_to "Logout", signout_path, method: :delete %>
      </li>
    </ul>
  </div>
</nav>